[package]
name = "alligregator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
